/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_albertomartinez;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Alberto
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_usuarios = new javax.swing.JDialog();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_edad = new javax.swing.JTextField();
        pf_pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_listarusuario = new javax.swing.JList<>();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        JD_canciones = new javax.swing.JDialog();
        tf_nombrecancion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_artistacancion = new javax.swing.JTextField();
        tf_duracion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_genero = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_listaralbum = new javax.swing.JList<>();
        jButton10 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JD_albums = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        tf_nombrealbum = new javax.swing.JTextField();
        tf_artistaalbum = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_albums = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_cancionesdealbum = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        JD_login = new javax.swing.JDialog();
        tf_loginuser = new javax.swing.JTextField();
        pf_loginpass = new javax.swing.JPasswordField();
        jButton14 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        JD_submenu = new javax.swing.JDialog();
        jButton15 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tf_nombreplaylist = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtree_listarplaylist = new javax.swing.JTree();
        jButton18 = new javax.swing.JButton();
        JD_explorar = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_exploraralbums = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_explorarcanciones = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_tusplaylist = new javax.swing.JList<>();
        jLabel20 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        b_canciones = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jButton7.setText("Crear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setText("Crear Usuario");

        tf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Password");

        jl_listarusuario.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_listarusuario);

        jButton8.setText("Listar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Eliminar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel5.setText("Username");

        javax.swing.GroupLayout JD_usuariosLayout = new javax.swing.GroupLayout(JD_usuarios.getContentPane());
        JD_usuarios.getContentPane().setLayout(JD_usuariosLayout);
        JD_usuariosLayout.setHorizontalGroup(
            JD_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_usuariosLayout.createSequentialGroup()
                .addGroup(JD_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_usuariosLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1)
                        .addGap(224, 224, 224)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_usuariosLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(JD_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(JD_usuariosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(JD_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGap(22, 22, 22)
                        .addGroup(JD_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(190, 190, 190)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_usuariosLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24)
                        .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_usuariosLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton7)
                        .addGap(231, 231, 231)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        JD_usuariosLayout.setVerticalGroup(
            JD_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_usuariosLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(JD_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_usuariosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JD_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_usuariosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5))
                    .addGroup(JD_usuariosLayout.createSequentialGroup()
                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_usuariosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(JD_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JD_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_usuariosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton7))
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        JD_canciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JD_cancionesMouseMoved(evt);
            }
        });

        jLabel6.setText("Agregar cancion a un album");

        jLabel7.setText("Nombre");

        jl_listaralbum.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_listaralbum);

        jButton10.setText("agregar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel8.setText("Artista");

        jLabel9.setText("Duracion");

        jLabel10.setText("Genero");

        jLabel11.setText("Eliga el album adonde se agregara la cancion");

        javax.swing.GroupLayout JD_cancionesLayout = new javax.swing.GroupLayout(JD_canciones.getContentPane());
        JD_canciones.getContentPane().setLayout(JD_cancionesLayout);
        JD_cancionesLayout.setHorizontalGroup(
            JD_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_cancionesLayout.createSequentialGroup()
                .addGroup(JD_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_cancionesLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel6))
                    .addGroup(JD_cancionesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7)
                        .addGap(43, 43, 43)
                        .addComponent(tf_nombrecancion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_cancionesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8)
                        .addGap(48, 48, 48)
                        .addComponent(tf_artistacancion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_cancionesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9)
                        .addGap(38, 38, 38)
                        .addComponent(tf_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_cancionesLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_cancionesLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_cancionesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(JD_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(JD_cancionesLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(45, 45, 45)
                                .addComponent(tf_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        JD_cancionesLayout.setVerticalGroup(
            JD_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_cancionesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addGroup(JD_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombrecancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(JD_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tf_artistacancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(JD_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tf_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(JD_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_cancionesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))
                    .addComponent(tf_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel12.setText("Crear album");

        jl_albums.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_albums);

        jt_cancionesdealbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Artista", "Genero", "Duracion"
            }
        ));
        jScrollPane4.setViewportView(jt_cancionesdealbum);

        jButton11.setText("Actualizar lista de albums");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Crear");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Mostrar canciones de album seleccionado");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel13.setText("Nombre");

        jLabel14.setText("Artista");

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_albumsLayout = new javax.swing.GroupLayout(JD_albums.getContentPane());
        JD_albums.getContentPane().setLayout(JD_albumsLayout);
        JD_albumsLayout.setHorizontalGroup(
            JD_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_albumsLayout.createSequentialGroup()
                .addGroup(JD_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_albumsLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel12))
                    .addGroup(JD_albumsLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(JD_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_albumsLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(23, 23, 23)
                                .addComponent(tf_nombrealbum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_albumsLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(28, 28, 28)
                                .addComponent(tf_artistaalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_albumsLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(230, 230, 230)
                        .addGroup(JD_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JD_albumsLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton2))))
                    .addGroup(JD_albumsLayout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jButton13))
                    .addGroup(JD_albumsLayout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        JD_albumsLayout.setVerticalGroup(
            JD_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_albumsLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addGroup(JD_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_albumsLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(JD_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(tf_nombrealbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(JD_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(tf_artistaalbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(JD_albumsLayout.createSequentialGroup()
                            .addComponent(jButton11)
                            .addGap(7, 7, 7)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jButton13)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jButton14.setText("GO");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel15.setText("LOGIN");

        jLabel16.setText("Username");

        jLabel17.setText("Password");

        javax.swing.GroupLayout JD_loginLayout = new javax.swing.GroupLayout(JD_login.getContentPane());
        JD_login.getContentPane().setLayout(JD_loginLayout);
        JD_loginLayout.setHorizontalGroup(
            JD_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_loginLayout.createSequentialGroup()
                .addGroup(JD_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_loginLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(JD_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(JD_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_loginuser)
                            .addComponent(pf_loginpass, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_loginLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel15)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        JD_loginLayout.setVerticalGroup(
            JD_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(29, 29, 29)
                .addGroup(JD_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JD_loginLayout.createSequentialGroup()
                        .addGroup(JD_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_loginuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(JD_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pf_loginpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        JD_submenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JD_submenuMouseMoved(evt);
            }
        });

        jButton15.setText("Explorar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel18.setText("Crear Playlist");

        jLabel19.setText("Nombre");

        jButton16.setText("Crear Playlist");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Playlists");
        jtree_listarplaylist.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane8.setViewportView(jtree_listarplaylist);

        jButton18.setText("Guardar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_submenuLayout = new javax.swing.GroupLayout(JD_submenu.getContentPane());
        JD_submenu.getContentPane().setLayout(JD_submenuLayout);
        JD_submenuLayout.setHorizontalGroup(
            JD_submenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_submenuLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(JD_submenuLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton18)
                .addGap(58, 58, 58))
            .addGroup(JD_submenuLayout.createSequentialGroup()
                .addGroup(JD_submenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_submenuLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_nombreplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_submenuLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_submenuLayout.setVerticalGroup(
            JD_submenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_submenuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(JD_submenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton18))
                .addGap(76, 76, 76)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(JD_submenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombreplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_submenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        JD_explorar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JD_explorarMouseClicked(evt);
            }
        });

        jl_exploraralbums.setModel(new DefaultListModel());
        jl_exploraralbums.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_exploraralbumsMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jl_exploraralbums);

        jl_explorarcanciones.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(jl_explorarcanciones);

        jl_tusplaylist.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jl_tusplaylist);

        jLabel20.setText("Albums");

        jButton17.setText("Agregar a la Playlist");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel21.setText("Canciones");

        jLabel22.setText("Tus Playlist");

        jLabel23.setText("Selecciona una cancion!");

        javax.swing.GroupLayout JD_explorarLayout = new javax.swing.GroupLayout(JD_explorar.getContentPane());
        JD_explorar.getContentPane().setLayout(JD_explorarLayout);
        JD_explorarLayout.setHorizontalGroup(
            JD_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_explorarLayout.createSequentialGroup()
                .addGroup(JD_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_explorarLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel20)
                        .addGap(126, 126, 126))
                    .addGroup(JD_explorarLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(JD_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(jScrollPane6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(JD_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_explorarLayout.createSequentialGroup()
                        .addGroup(JD_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_explorarLayout.createSequentialGroup()
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_explorarLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(163, 163, 163))))
            .addGroup(JD_explorarLayout.createSequentialGroup()
                .addGroup(JD_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_explorarLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel21))
                    .addGroup(JD_explorarLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel23)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_explorarLayout.setVerticalGroup(
            JD_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_explorarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(JD_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JD_explorarLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGroup(JD_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_explorarLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_explorarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jButton1.setText("Usuarios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b_canciones.setText("Canciones");
        b_canciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancionesActionPerformed(evt);
            }
        });

        jButton3.setText("Albums");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Log in");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Guardar Usuarios");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cargar Usuarios");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_canciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(b_canciones)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Crear Usuario
        String nombre, user,pass;
        int edad;
        int resp=0;
        
        try {
            nombre = tf_nombre.getText();
            user=tf_user.getText();
            pass=pf_pass.getText();
            if (tf_edad.getText().equals("")) {
                edad=0;
            }else{
              edad=Integer.parseInt(tf_edad.getText());  
            }
            
            if (nombre.equals("")) {
                resp=1;
            }
            if (user.equals("")) {
                resp=1;
            }
            if (pass.equals("")) {
                resp=1;
            }
            if (tf_edad.getText().equals("")||edad==0) {
                resp=1;
            }
            
                
            for (int i = 0; i < usuarios.size(); i++) {
                
                if(usuarios.get(i).getNombre().equalsIgnoreCase(nombre)){
                    resp=2;
                    
                }
            }
            
            //guardar
            if (resp==0) {
                
            
            usuarios.add(new Usuario(nombre, edad, user, pass));
            
            JOptionPane.showMessageDialog(JD_usuarios, "Cuenta Creada Exitosamente");
                
            //resetear controles
            tf_nombre.setText("");
            tf_user.setText("");
            tf_edad.setText("");
            pf_pass.setText("");
            }
            if (resp==2) {
                JOptionPane.showMessageDialog(JD_usuarios, "Ese nombre ya fue ingresado, intente con otro");
            }
            if(resp==1){
                JOptionPane.showMessageDialog(JD_usuarios, "Olvido llenar algun campo!");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(JD_usuarios, "Ocurrio un error y no se creo una cuenta");
            
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JD_usuarios.pack();
        JD_usuarios.setLocationRelativeTo(this);
        JD_usuarios.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b_cancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancionesActionPerformed
        JD_canciones.pack();
        JD_canciones.setLocationRelativeTo(this);
        JD_canciones.setVisible(true);
    }//GEN-LAST:event_b_cancionesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JD_albums.pack();
        JD_albums.setLocationRelativeTo(this);
        JD_albums.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JD_login.pack();
        JD_login.setLocationRelativeTo(this);
        JD_login.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        am.datos.clear();
        for (int i = 0; i < usuarios.size(); i++) {
            am.datos.add(usuarios.get(i));
        }
        for (int i = 0; i < albums.size(); i++) {
            am.datos.add(albums.get(i));
        }
        am.escribirArchivo();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        am.cargarArchivo();
        usuarios.clear();
        albums.clear();
        for (int i = 0; i < am.datos.size(); i++) {
            if (am.datos.get(i) instanceof Usuario) {
                usuarios.add((Usuario)am.datos.get(i));
            }
            if (am.datos.get(i) instanceof Album) {
                albums.add((Album)am.datos.get(i));
            }
        }
        am.escribirArchivo();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // listar usuarios
        DefaultListModel modelo=(DefaultListModel) jl_listarusuario.getModel();
        modelo.removeAllElements();
        for (int i = 0; i <usuarios.size() ; i++) {
            modelo.addElement(usuarios.get(i));
        }

        jl_listarusuario.setModel(modelo);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // eliminar usuario
         if (jl_listarusuario.getSelectedIndex()>=0){
            DefaultListModel modelo=(DefaultListModel) jl_listarusuario.getModel();
            String nombre=((Usuario)modelo.get(jl_listarusuario.getSelectedIndex())).getNombre();
            
             for (int i = 0; i < usuarios.size(); i++) {
                 if (usuarios.get(i).getNombre().equals(nombre)) {
                     usuarios.remove(i);
                 }
             }

        }else{
            JOptionPane.showMessageDialog(JD_usuarios, "No selecciono ningun usuario!");
        }
        DefaultListModel modelo=(DefaultListModel) jl_listarusuario.getModel();
        modelo.removeAllElements();
        for (int i = 0; i <usuarios.size() ; i++) {
            modelo.addElement(usuarios.get(i));
        }

        jl_listarusuario.setModel(modelo);
         
    }//GEN-LAST:event_jButton9ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        //verificar si hay album o no
        if (albums.isEmpty()) {
            b_canciones.setEnabled(false);
        }else{
            b_canciones.setEnabled(true);
        }
        
        DefaultListModel modelo=(DefaultListModel) jl_listaralbum.getModel();
        modelo.removeAllElements();
        for (int i = 0; i <albums.size() ; i++) {
            modelo.addElement(albums.get(i));
        }

        jl_listaralbum.setModel(modelo);
    }//GEN-LAST:event_formMouseMoved

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        //crear album
        String nombre, artista;
        int resp=0;
        
        try {
            nombre = tf_nombrealbum.getText();
            artista=tf_artistaalbum.getText();

            
            if (nombre.equals("")) {
                resp=1;
            }
            if (artista.equals("")) {
                resp=1;
            }
            
                
            for (int i = 0; i < albums.size(); i++) {
                
                if(albums.get(i).getNombre().equalsIgnoreCase(nombre)){
                    resp=2;
                    
                }
            }
            
            //guardar
            if (resp==0) {
                
            
            albums.add(new Album(nombre, artista));
            
            JOptionPane.showMessageDialog(JD_albums, "Album Creado Exitosamente");
                
            //resetear controles
            tf_nombrealbum.setText("");
            tf_artistaalbum.setText("");
            }
            if (resp==2) {
                JOptionPane.showMessageDialog(JD_albums, "Ese nombre ya fue ingresado, intente con otro");
            }
            if(resp==1){
                JOptionPane.showMessageDialog(JD_albums, "Olvido llenar algun campo!");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(JD_albums, "Ocurrio un error y no se creo una cuenta");
            
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    DefaultListModel modelo=(DefaultListModel) jl_albums.getModel();
        modelo.removeAllElements();
        for (int i = 0; i <albums.size() ; i++) {
            modelo.addElement(albums.get(i));
        }

        jl_albums.setModel(modelo);
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // eliminar album
        if (jl_albums.getSelectedIndex()>=0){
            DefaultListModel modelo=(DefaultListModel) jl_albums.getModel();
            String nombre=((Album)modelo.get(jl_albums.getSelectedIndex())).getNombre();
            
             for (int i = 0; i < albums.size(); i++) {
                 if (albums.get(i).getNombre().equals(nombre)) {
                     albums.remove(i);
                 }
             }

        }else{
            JOptionPane.showMessageDialog(JD_albums, "No selecciono ningun album!");
        }
        DefaultListModel modelo=(DefaultListModel) jl_albums.getModel();
        modelo.removeAllElements();
        for (int i = 0; i <albums.size() ; i++) {
            modelo.addElement(albums.get(i));
        }

        jl_albums.setModel(modelo);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JD_cancionesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JD_cancionesMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_JD_cancionesMouseMoved

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // Agregar cancion
        if (jl_listaralbum.getSelectedIndex()>=0){
            DefaultListModel modelo=(DefaultListModel) jl_listaralbum.getModel();
            ((Album)modelo.get(jl_listaralbum.getSelectedIndex())).canciones.add(new Cancion(tf_nombrecancion.getText(), Double.parseDouble(tf_duracion.getText()),tf_artistacancion.getText(), tf_genero.getText()));
            JOptionPane.showMessageDialog(JD_canciones, "Cancion agregada con exito!");
            
            tf_nombrecancion.setText("");
            tf_duracion.setText("");
            tf_artistacancion.setText("");
            tf_genero.setText("");
        }else{
            JOptionPane.showMessageDialog(JD_canciones, "No selecciono ningun usuario!");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        if (jl_albums.getSelectedIndex()>=0){
            DefaultListModel modelo=(DefaultListModel) jl_albums.getModel();
        
            DefaultTableModel modelo2=(DefaultTableModel)jt_cancionesdealbum.getModel();

            for (int i = 0; i < ((Album)modelo.get(jl_albums.getSelectedIndex())).canciones.size(); i++) {
                Object[] newrow={
                   ((Album)modelo.get(jl_albums.getSelectedIndex())).canciones.get(i).getNombre(), ((Album)modelo.get(jl_albums.getSelectedIndex())).canciones.get(i).getArtista(), ((Album)modelo.get(jl_albums.getSelectedIndex())).canciones.get(i).genero,((Album)modelo.get(jl_albums.getSelectedIndex())).canciones.get(i).getDuracion()
                };
                modelo2.addRow(newrow);
                jt_cancionesdealbum.setModel(modelo2);
                
            }
        
        
        }else{
            JOptionPane.showMessageDialog(JD_albums, "No selecciono ningun album!");
        }
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // login
        int resp=3;
        for (int i = 0; i < usuarios.size(); i++) {
                if(usuarios.get(i).getUsername().equalsIgnoreCase(tf_loginuser.getText()) && usuarios.get(i).getPassword().equals(pf_loginpass.getText())){
                    usuarioactual=i;
                    
                    DefaultTreeModel modelo=(DefaultTreeModel)jtree_listarplaylist.getModel();
                    DefaultMutableTreeNode raiz=(DefaultMutableTreeNode) modelo.getRoot();
                    
                    
                    for (int j = 0; j < usuarios.get(usuarioactual).playlists.size(); j++) {
                        DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(usuarios.get(usuarioactual).playlists.get(j));
                        for (int k = 0; k < usuarios.get(usuarioactual).playlists.get(i).canciones.size(); k++) {
                            nodo.add(new DefaultMutableTreeNode(usuarios.get(usuarioactual).playlists.get(i).canciones.get(k)));
                        }
                        raiz.add(nodo);
                    }
                    modelo.reload();
                    
                    
                    
                    JD_submenu.pack();
                    JD_submenu.setLocationRelativeTo(JD_login);
                    JD_submenu.setVisible(true);
                    resp=1;
                    
                    tf_loginuser.setText("");
                    pf_loginpass.setText("");
                }else{
                    if(resp!=1){
                        resp=3;
                    }
                }
        }
                    if(resp==3){
                JOptionPane.showMessageDialog(JD_login, "Usuario o contraseña incorrecta");
            } 
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // abrir explorar
        JD_explorar.pack();
        JD_explorar.setLocationRelativeTo(JD_submenu);
        JD_explorar.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // crear playlist
        if (tf_nombreplaylist.getText().equals("")) {
            JOptionPane.showMessageDialog(JD_submenu, "No le pusiste nombre!");
        }else{
            usuarios.get(usuarioactual).playlists.add(new Playlist(tf_nombreplaylist.getText()));
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void JD_submenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JD_submenuMouseMoved
        // actualizar tablas de explorar
        
        DefaultListModel modelo=(DefaultListModel) jl_exploraralbums.getModel();
        modelo.removeAllElements();
        for (int i = 0; i <albums.size() ; i++) {
            modelo.addElement(albums.get(i));
        }

        jl_exploraralbums.setModel(modelo);
        
        DefaultListModel modelo2=(DefaultListModel) jl_tusplaylist.getModel();
        modelo2.removeAllElements();
        for (int i = 0; i <usuarios.get(usuarioactual).playlists.size() ; i++) {
            modelo2.addElement(usuarios.get(usuarioactual).playlists.get(i));
        }

        jl_tusplaylist.setModel(modelo2);
    }//GEN-LAST:event_JD_submenuMouseMoved

    private void jl_exploraralbumsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_exploraralbumsMouseClicked
        // TODO add your handling code here:
        
        DefaultListModel modelo=(DefaultListModel) jl_explorarcanciones.getModel();
        DefaultListModel modelo2=(DefaultListModel) jl_exploraralbums.getModel();
        modelo.removeAllElements();
        if (((Album)modelo2.get(jl_exploraralbums.getSelectedIndex())).canciones.isEmpty()) {
            modelo.addElement("Este album no tiene canciones");
        }
        for (int i = 0; i <((Album)modelo2.get(jl_exploraralbums.getSelectedIndex())).canciones.size() ; i++) {
            modelo.addElement(((Album)modelo2.get(jl_exploraralbums.getSelectedIndex())).canciones.get(i));
            
        }

        jl_explorarcanciones.setModel(modelo);
    }//GEN-LAST:event_jl_exploraralbumsMouseClicked

    private void JD_explorarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JD_explorarMouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo=(DefaultListModel) jl_explorarcanciones.getModel();
        modelo.removeAllElements();
        jl_explorarcanciones.setModel(modelo);
    }//GEN-LAST:event_JD_explorarMouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:DefaultListModel modelo=(DefaultListModel) jl_explorarcanciones.getModel();
         if (jl_explorarcanciones.getSelectedIndex()>=0){
            if (jl_tusplaylist.getSelectedIndex()>=0){
         
                
                    
                
                DefaultListModel modelo=(DefaultListModel) jl_explorarcanciones.getModel();
                DefaultListModel modelo2=(DefaultListModel) jl_tusplaylist.getModel();      

                usuarios.get(usuarioactual).playlists.get(jl_tusplaylist.getSelectedIndex()).canciones.add(((Cancion)modelo.get(jl_explorarcanciones.getSelectedIndex())));
                JOptionPane.showMessageDialog(JD_explorar, "Cancion agregada!");
                
            }else{
                JOptionPane.showMessageDialog(JD_explorar, "No selecciono una playlist!");
            }
            
         }else{
            JOptionPane.showMessageDialog(JD_explorar, "No selecciono una cancion!"); 
         }

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        am.datos.clear();
        for (int i = 0; i < usuarios.size(); i++) {
            am.datos.add(usuarios.get(i));
        }
        for (int i = 0; i < albums.size(); i++) {
            am.datos.add(albums.get(i));
        }
        am.escribirArchivo();
    }//GEN-LAST:event_jButton18ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JD_albums;
    private javax.swing.JDialog JD_canciones;
    private javax.swing.JDialog JD_explorar;
    private javax.swing.JDialog JD_login;
    private javax.swing.JDialog JD_submenu;
    private javax.swing.JDialog JD_usuarios;
    private javax.swing.JButton b_canciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JList<String> jl_albums;
    private javax.swing.JList<String> jl_exploraralbums;
    private javax.swing.JList<String> jl_explorarcanciones;
    private javax.swing.JList<String> jl_listaralbum;
    private javax.swing.JList<String> jl_listarusuario;
    private javax.swing.JList<String> jl_tusplaylist;
    private javax.swing.JTable jt_cancionesdealbum;
    private javax.swing.JTree jtree_listarplaylist;
    private javax.swing.JPasswordField pf_loginpass;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JTextField tf_artistaalbum;
    private javax.swing.JTextField tf_artistacancion;
    private javax.swing.JTextField tf_duracion;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_genero;
    private javax.swing.JTextField tf_loginuser;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombrealbum;
    private javax.swing.JTextField tf_nombrecancion;
    private javax.swing.JTextField tf_nombreplaylist;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
    Admin am=new Admin("./datos.alb");
    ArrayList <Album> albums=new ArrayList();
    ArrayList <Usuario>usuarios=new ArrayList();
    int usuarioactual;
    
}
